### PR TITLE
major size optimisation

### PR DESCRIPTION
**Pull request by peterferrie**

### CODE REVIEW

**Comment by XlogicX** [comment]
Lots of cool optimization hacks and it also fixed the bug where the 'snake' stops on an item.

However, it seemed to have broken the scoring system; it barely gets into the blue-backround score and then loops back to the starting black background. The game is actually unwinnable with this.

I hope it was a simple thing that broke that, because there are some worth while optimizations here.

**Comment by peterferrie** [comment]
> Lots of cool optimization hacks and it also fixed the bug where the 'snake'
> stops on an item.

Yes, I noticed that, too.  It's more like the original game now.

> However, it seemed to have broken the scoring system; it barely gets into
> the blue-backround score and then loops back to the starting black
> background. The game is actually unwinnable with this.

The game is still winnable but only in a restricted case - you have to
stop picking up items when the score reaches the 0xdfxx range, and
hope that you have enough room to move until it hits 0xf600.  It's not
ideal. ;-)

> I hope it was a simple thing that broke that, because there are some worth
> while optimizations here.

I've submitted a fix for it.

**Comment by XlogicX** [comment]
Ok yeah, that was worth fixing for sure, but actually not the source of the problem I was referring to; it's actually looping WAY before it gets to that point.

I'm sure you already know, but worth repeating for the context of this issue, the score increments through all the characters, then through all the font colors, and then through all the background colors. So I see the font color go through all rotations for black background. Next it goes to blue background, and maybe goes through font colors of black, blue, and green, and then loops back down to black background again.

To be more precise(ish) about the the score; it starts looping back to 'zero' when it get's up to a score of around 4,864. The winning score is 62,976 (0xf600). So at the point of a sub 5,000 score, overflowing is VERY unlikely.

I haven't picked through your changes enough to figure out what would cause that though :(.

Regardless, I still want to implement a lot of your optimizations that wouldn't effect the scoring. Like all the places you move to ah or al when I move an entire 2-bytes into ax even though one of the bytes is null (assuming that part of the register was supposed to previously be null...)

I don't want to put too much stress on ya, but I am only comfortable merging when I can properly win the game (in practice, not theory). If the game get's too hard or fast to test this, just change line 72: add ax, 4         ;#CHEAT, default is 4; make amount higher for overall slower (but still progressive) game

**Comment by XlogicX** [comment]
I beleive i found it, and some other things. I will merge later today and patch it with fixes.

**Pull request merged**
